dist: bionic
jobs:
  include:
    - name: Ubuntu Bionic Beaver (18.04 LTS)
      env:
        - DOCKER_DIST=ubuntu
        - DOCKER_VERSION=bionic
    - name: Ubuntu Cosmic Cuttlefish (18.10)
      env:
        - DOCKER_DIST=ubuntu
        - DOCKER_VERSION=cosmic
    - name: Ubuntu Disco Dingo (19.04)
      env:
        - DOCKER_DIST=ubuntu
        - DOCKER_VERSION=disco
    - name: Ubuntu Eoan Ermine (19.10)
      env:
        - DOCKER_DIST=ubuntu
        - DOCKER_VERSION=eoan
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - DOCKER_IMAGE_NAME=openhoi-ogre-package:${DOCKER_DIST}-${DOCKER_VERSION}
  - echo -e "FROM ${DOCKER_DIST}:${DOCKER_VERSION}\nADD . /openhoi\nRUN cd /openhoi\nRUN ls -lah\nRUN ./package" | docker build -t $DOCKER_IMAGE_NAME -
  - docker run $DOCKER_IMAGE_NAME