language: cpp
sudo: required
matrix:
  include:
    - name: Ubuntu Bionic LTS Clang 7
      os: linux
      dist: bionic
      compiler: clang
script:
  - source package n
before_script:
  - chmod +x package
notifications:
  email: false
branches:
  only:
    - /^v.+$/
git:
  depth: 3
before_deploy:
  - git config --local user.name "openhoi robot"
  - git config --local user.email "robot@openhoi.net"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: dependencies.openhoi.net
    local_dir: build/package
    upload-dir: ogre
    acl: public_read
    region: eu-central-1
    skip_cleanup: true
    on:
      all_branches: true
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: build/package/ogre_$OGRE_VERSION.deb
    skip_cleanup: true
    draft: true
    overwrite: true
    body: Automatically built Ubuntu %TRAVIS_DIST% release of $OGRE_VERSION