language: cpp
sudo: required
matrix:
  include:
    - name: Ubuntu Bionic LTS Clang 7
      os: linux
      dist: bionic
      compiler: clang
script:
  - source package n
before_script:
  - chmod +x package
notifications:
  email: false
branches:
  only:
    - /^v.*$/
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: openhoi
  local_dir: build/package
  upload-dir: dependencies/ogre-package
  skip_cleanup: true