shallow_clone: false
branches:
  only:
    - /v.*/
image: Visual Studio 2017
clone_depth: 3
platform: x64
before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - cd C:\projects\ogre-package
build_script:
  - package
after_build:
  - ps: Remove-Item *.7z
  - ps: Copy-Item build/package/*.7z -Destination .
  - set OGRE_VERSION=%APPVEYOR_REPO_BRANCH:~1%
notifications:
  - provider: Email 
    on_build_success: false 
    on_build_failure: false 
    on_build_status_changed: false
artifacts:
  - path: ogre_msvc_%OGRE_VERSION%.7z
    name: MSVC
deploy:
  - provider: S3
    access_key_id: "%AWS_ACCESS_KEY_ID%"
    secret_access_key: "%AWS_SECRET_KEY%"
    bucket: dependencies.openhoi.net
    region: eu-central-1
    set_public: true
    folder: ogre
    artifact: MSVC
#  - provider: GitHub
#    description: Automatically built Windows release of %OGRE_VERSION%
#    release: msvc_%OGRE_VERSION%
#    auth_token: "%GITHUB_OAUTH_TOKEN%"
#    artifact: MSVC
#    draft: false
#    force_update: true
#    skip_tags: true
#    tag: msvc_%OGRE_VERSION%_%APPVEYOR_BUILD_ID%