#!/bin/bash

##############################################################################
##                                                                          ##
## Tool to build and (if requested) to deploy OGRE library for *NIX         ##
## !DO NOT RUN THIS SCRIPT AS ROOT!                                         ##
##                                                                          ##
##############################################################################




# Do some preparations...
if [[ $OSTYPE == "darwin"* ]]; then
    MACOS=true
    CHECKMARK="\xE2\x9C\x94"
    CROSSMARK="\xE2\x9C\x96"
    LINEBEG="\xE2\x98\x85"
elif (locale | grep -e 'utf8' -e 'UTF-8') >/dev/null 2>&1; then
    CHECKMARK="\u2714"
    CROSSMARK="\u2716"
    LINEBEG="\u2605"
else
    CHECKMARK="[Y]"
    CROSSMARK="[X]"
    LINEBEG="::"
fi
CHECKMARK="\e[1;32m$CHECKMARK\e[0m"
CROSSMARK="\e[1;91m$CROSSMARK\e[0m"
LINEBEG="\e[1;34m$LINEBEG\e[0m"
CWD=$PWD




# At first, ensure that we are not root as some commands we execute are not recommended
# to be called with root permissions. This check won't be performed in case we are inside Docker!
if [ -f /.dockerenv ]; then
    printf "$LINEBEG We are inside a Docker container!\n"
else
    if [[ $(id -u) -eq 0 ]]; then
        printf " $CROSSMARK Please do not run this script with root permissions.\n"
        exit;
    fi
fi




# Then, check, if we shall only do the build
BUILD_ONLY=$1




# Then, check for the current OS type and define build/packaging dependencies
printf "$LINEBEG Checking for operating system type...\n"

INSTALLSYSTEMS=(PACMAN APTGET HOMEBREW PKG)
isa=${#INSTALLSYSTEMS[@]}
for ((i=0; i < $isa; i++)); do
    ISE_NAME=${INSTALLSYSTEMS[i]}
    declare -r ${ISE_NAME}=$i
done

if [ $OSTYPE == "linux-gnu" ]; then
    # Linux
    printf " $CHECKMARK Linux is supported, but we need to check for your installed distribution...\n"
    
    # Get current Linux distribution
    if [ -f /etc/arch-release ]; then
        DISTRO="arch"
    else
        DISTRO=$(lsb_release -is)
    fi
    DISTRO=${DISTRO,,} # Make distro name lower-case
    if [[ $DISTRO == "arch" ]]; then
        printf " $CHECKMARK Arch Linux is supported. Using \e[1mpacman\e[0m install system...\n"

        INSTALLSYSTEM=${INSTALLSYSTEMS[$PACMAN]}
        PACKAGES="base-devel git cmake zlib sdl2"
    elif [ $DISTRO == "debian" ] || [ $DISTRO == "ubuntu" ]; then
        if [ $DISTRO == "ubuntu" ]; then
            printf " $CHECKMARK Ubuntu is supported. Using \e[1mapt-get\e[0m install system...\n"
        else
            printf " $CHECKMARK Debian is supported. Using \e[1mapt-get\e[0m install system...\n"
        fi

        #CODENAME=`lsb_release --codename | cut -f2`
        INSTALLSYSTEM=${INSTALLSYSTEMS[$APTGET]}
        PACKAGES="git build-essential cmake dput dh-make fakeroot devscripts lintian libfreetype6-dev libfreeimage-dev libsdl2-dev libx11-dev libgl1-mesa-dev libxrandr-dev libxt-dev libxaw7-dev zlib1g-dev"
    else
        printf " $CROSSMARK Your distribution '$DISTRO' is not supported. Aborting.\n"
        exit 1 
    fi
elif [[ $MACOS == true ]]; then
    printf " $CHECKMARK macOS is supported.\n"
    
    INSTALLSYSTEM=${INSTALLSYSTEMS[$HOMEBREW]}
    PACKAGES=(cmake zlib freeimage freetype sdl2)
else
    printf " $CROSSMARK Your OS '$OSTYPE' is not supported. Aborting.\n"
    exit 1 
fi




# Install all required packages...
if [ $INSTALLSYSTEM ]; then
    printf "$LINEBEG Installing required packages...\n"

    if [ $INSTALLSYSTEM == ${INSTALLSYSTEMS[$PACMAN]} ]; then
        sudo pacman -Syu --noconfirm
        sudo pacman -S $PACKAGES --noconfirm --needed

        if [ $AUR_PACKAGES ]; then
            mkdir --parents build/pacman_aur
            for i in "${AUR_PACKAGES[@]}"
            do
                if [ ! -d "tmp/$i" ]; then
                    git clone https://aur.archlinux.org/$i.git build/pacman_aur/$i
                else
                    git -C build/pacman_aur/$i pull
                fi
                pushd build/pacman_aur/$i
                rm *.pkg.tar.xz
                makepkg -Acs --noconfirm --needed
                popd >/dev/null
                sudo pacman -U $(ls build/pacman_aur/$i/*.pkg.tar.xz | head -1) --noconfirm
            done
        fi
    elif [ $INSTALLSYSTEM == ${INSTALLSYSTEMS[$APTGET]} ]; then
        sudo apt-get update -qy
        sudo apt-get upgrade -qy
        sudo apt-get install -qy --no-install-recommends $PACKAGES
	    sudo apt-get clean
    elif [ $INSTALLSYSTEM == ${INSTALLSYSTEMS[$PKG]} ]; then
        sudo freebsd-update fetch --not-running-from-cron
        sudo freebsd-update install --not-running-from-cron
        env ASSUME_ALWAYS_YES=YES pkg bootstrap
        sudo pkg -N install $PACKAGES
    elif [ $INSTALLSYSTEM == ${INSTALLSYSTEMS[$HOMEBREW]} ]; then
        command -v brew >/dev/null 2>&1 || { /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; }
        for i in "${PACKAGES[@]}"
        do
            brew ls --versions $i && brew upgrade $i || brew install $i
        done
    fi

    printf " $CHECKMARK Finished! Please check the above command line output in order to verify that everything was okay.\n"
fi




# Cleanup and preparations
printf "$LINEBEG Cleanup and preparations...\n"

source version
OGRE_VERSION=$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH
OGRE_TAG=v$OGRE_VERSION

if [ -d build ]; then
    # Reset OGRE Overlay code
    rm -R ogre/Components/Overlay/src/imgui
fi

git -C ogre reset --hard $OGRE_TAG

# Sync submodules
git submodule update --init --recursive --remote

# Link imgui sources with OGRE Overlay
rm -rf ogre/Components/Overlay/src/imgui
ln -s imgui ogre/Components/Overlay/src/imgui




# Compile OGRE
printf "$LINEBEG Compiling OGRE...\n"

if [ -d build ]; then rm -rf build; fi
mkdir build
cd build
cmake -DOGRE_BUILD_TESTS=OFF -DOGRE_BUILD_SAMPLES=OFF -DOGRE_INSTALL_SAMPLES=OFF -DOGRE_BUILD_TOOLS=OFF -DOGRE_INSTALL_TOOLS=OFF -DOGRE_INSTALL_DOCS=OFF \
      -DOGRE_CONFIG_DOUBLE=OFF -DOGRE_CONFIG_ENABLE_DDS=ON -DOGRE_CONFIG_ENABLE_ETC=OFF -DOGRE_CONFIG_ENABLE_ZIP=OFF -DOGRE_CONFIG_ENABLE_ETC=OFF \
      -DOGRE_BUILD_COMPONENT_PYTHON=OFF -DOGRE_BUILD_PLUGIN_BSP=OFF -DOGRE_BUILD_PLUGIN_OCTREE=OFF -DOGRE_BUILD_PLUGIN_PCZ=OFF -DOGRE_BUILD_PLUGIN_PFX=ON \
      -DOGRE_BUILD_PLUGIN_DOT_SCENE=OFF -DOGRE_BUILD_COMPONENT_PAGING=OFF -DOGRE_BUILD_COMPONENT_TERRAIN=OFF -DOGRE_BUILD_COMPONENT_MESHLODGENERATOR=OFF \
      -DOGRE_BUILD_COMPONENT_VOLUME=OFF -DOGRE_BUILD_COMPONENT_BITES=OFF -DOGRE_BUILD_RENDERSYSTEM_GL=ON -DOGRE_STATIC=OFF -DOGRE_BUILD_COMPONENT_OVERLAY_IMGUI=ON \
      -DOpenGL_GL_PREFERENCE=LEGACY -DOGRE_BUILD_DEPENDENCIES=OFF -DCMAKE_BUILD_TYPE=Release ../cmake/
if [ "$BUILD_ONLY" = "y" ]; then
    make
    sudo make install
else
    make package
fi




# Copy package files to new directory
if [ "$TRAVIS" == "true" ]; then
    BINARY_NAME=ogre_${DOCKER_DIST}_${DOCKER_DIST_VERSION}_$OGRE_VERSION.deb
		BINARY_PATH=/openhoi-package/$BINARY_NAME
else
		if [ -d package ]; then rm -rf package; fi
		mkdir package
    BINARY_NAME=ogre_$OGRE_VERSION.deb
		BINARY_PATH=package/$BINARY_NAME
fi
printf "$LINEBEG Copying OGRE binary to $BINARY_PATH...\n"
cp ogre_$OGRE_VERSION.deb $BINARY_PATH
cd ..




# Reset OGRE Overlay code
printf "$LINEBEG Cleanup...\n"

rm -R ogre/Components/Overlay/src/imgui
git -C ogre reset --hard $OGRE_TAG